//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by remotemonitor.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_MYSTATIC                    105
#define ID_SCALESTATIC                  106
#define CG_IDD_MYDIALOGBAR              107
#define CG_ID_VIEW_MYDIALOGBAR          108
#define IDC_LISTCAR                     109
#define IDS_PROPSHT_CAPTION             110
#define IDD_FENJIINFO                   111
#define IDD_FENJIPARA                   112
#define IDR_MAINFRAME                   128
#define IDR_REMOTETYPE                  129
#define IDC_HAND                        139
#define IDC_PAN                         139
#define IDC_ZOOMIN                      140
#define IDC_ZOOMOUT                     141
#define IDD_PENPROPERTIES               141
#define IDD_MAPSELECT                   142
#define IDC_USERDRAW                    143
#define IDC_USERMOVING                  144
#define IDC_SELECT                      145
#define IDD_LOGIN                       146
#define IDD_SENDAADLG                   147
#define IDD_SENDCCDLG                   149
#define IDD_SENDCDDLG                   150
#define IDD_SENDABDLG                   151
#define IDD_SENDDADLG                   152
#define IDD_SETNODENUM                  154
#define IDD_DUTYRECORD                  155
#define IDD_JIAOBAN                     156
#define IDD_NODEINFO                    157
#define IDD_FENJINUM                    157
#define IDD_CHANGEFENJINUM              158
#define IDD_ADDORCHANGEUSER             159
#define IDD_ADDORCHANGEMAIN             160
#define IDD_CABLENUM                    161
#define IDD_CHANGECABLENUM              162
#define IDD_CABLEINFO                   163
#define IDD_FENJICABLESET               164
#define IDD_ADDFENJIINFO                165
#define IDD_CABLEINFOSET                166
#define IDD_USERSET                     167
#define IDD_ADDUSERDLG                  168
#define IDD_DUTYRECORDDLG               169
#define IDD_FENJICABLEVIEW              170
#define IDD_VIEWFENJIALARMINFO          171
#define IDD_VIEWCABLEALARMINFO          172
#define IDD_ADDCABLECONFIG              174
#define IDD_SENDCBDLG                   175
#define IDD_SETCENTERTELDLG             177
#define IDD_SENDDCDLG                   178
#define IDC_BUTTON1                     1000
#define IDC_ADD                         1000
#define IDC_ADD1                        1000
#define IDC_CHANGEFENJINUM              1000
#define IDC_COMBO1                      1001
#define IDC_PORT                        1001
#define IDC_DEL                         1001
#define IDC_CABLENUM                    1001
#define IDC_CHANGE1                     1001
#define IDC_CHANGE                      1001
#define IDC_COMBO2                      1002
#define IDC_BAUDRATE                    1002
#define IDC_NUM                         1002
#define IDC_DELETE1                     1002
#define IDC_DELETE                      1002
#define IDC_COMBO3                      1003
#define IDC_USERNAME                    1003
#define IDC_ADD2                        1003
#define IDC_COMBO6                      1003
#define IDC_COMBO4                      1004
#define IDC_CHANGE2                     1004
#define IDC_PENCOLORCOMBO               1005
#define IDC_DELETE2                     1005
#define IDC_PENWIDTHCOMBO               1006
#define IDC_BRUSHSTYLECOMBO             1008
#define IDC_MAPLIST                     1009
#define IDC_TEXTCOLOR                   1009
#define IDC_EDIT1                       1010
#define IDC_COFF                        1010
#define IDC_GBK                         1010
#define IDC_TELEEDIT                    1010
#define IDC_FENGJINUM                   1010
#define IDC_RECORD                      1010
#define IDC_EDIT2                       1011
#define IDC_PWD                         1011
#define IDC_SUBTELE                     1011
#define IDC_EDIT3                       1012
#define IDC_PASSWORD1                   1013
#define IDC_EDIT4                       1013
#define IDC_EDIT5                       1014
#define IDC_EDIT7                       1015
#define IDC_EDIT6                       1016
#define IDC_NODELIST                    1018
#define IDC_TELELIST                    1019
#define IDC_CABLELIST                   1020
#define IDC_SENDTELELIST                1020
#define IDC_BUFANG                      1022
#define IDC_CABLESTATIC                 1024
#define IDC_FENJITEL                    1027
#define IDC_ADRESS                      1028
#define IDC_USERINFOLIST                1029
#define IDC_MAINTENANCELIST             1030
#define IDC_DISPLAYFENJIINFO            1031
#define IDC_NUMEDIT                     1032
#define IDC_ObjectID                    1033
#define IDC_NEWFENJINUM                 1033
#define IDC_NAME                        1034
#define IDC_FENJINUM                    1034
#define IDC_CABLENUMBER                 1034
#define IDC_FENJINAME                   1035
#define IDC_EDIT_REMARK                 1036
#define IDC_TEL                         1036
#define IDC_FENJINUMBER                 1037
#define IDC_CHANGECABLENUM              1038
#define IDC_DISPLAYCABLEINFO            1039
#define IDC_CABLECOMBO                  1040
#define IDC_STARTADDR                   1043
#define IDC_ENDADDR                     1044
#define IDC_STATE                       1045
#define IDC_FENJILIST                   1046
#define IDC_LIST1                       1052
#define IDC_RIGHTB                      1055
#define IDC_RIGHTA                      1056
#define IDC_BUTTON_ADDTelephone         1057
#define IDC_RIGHTC                      1057
#define IDC_BUTTON_ADDTelephone2        1058
#define IDC_RIGHTD                      1058
#define IDC_LIST_TELEPHNOE              1059
#define IDC_DUTY                        1059
#define IDC_BUTTON_ADDTelephone3        1060
#define IDC_DEPARTMENT                  1060
#define IDC_ADDRESS                     1061
#define IDC_BUTTON2                     1062
#define IDC_MODECOMBO                   1063
#define IDC_BUTTON3                     1064
#define IDC_MODE1                       1065
#define IDC_MYSTATIC1                   1066
#define IDC_MYSTATIC2                   1067
#define IDC_PROBE1                      1068
#define IDC_PROBE2                      1070
#define IDC_PRINT2                      1071
#define IDC_RADIO1                      1071
#define IDC_MYSTATIC3                   1072
#define IDC_SPIN1                       1072
#define IDC_MYSTATIC4                   1073
#define IDC_RADIO2                      1073
#define IDC_MODE2                       1074
#define IDC_RADIO3                      1074
#define IDC_RADIO4                      1075
#define IDC_RADIO5                      1076
#define IDC_RADIO6                      1077
#define IDC_RADIO7                      1078
#define IDC_PROBE                       1079
#define IDC_SPIN2                       1080
#define IDC_SPIN3                       1081
#define IDC_SPIN4                       1082
#define IDC_SPIN7                       1083
#define IDC_NEWFENJINUMBER              1086
#define IDC_CHECK1                      1087
#define IDC_EXPORT1                     1088
#define IDC_EXPORT2                     1089
#define IDC_EXPORT3                     1090
#define IDC_EXPORT4                     1091
#define ID_ZOOMIN                       32771
#define ID_ZOOMOUT                      32772
#define ID_PAN                          32773
#define ID_BUTTON32778                  32778
#define ID_BUTTON32780                  32780
#define ID_BUTTON32781                  32781
#define ID_BUTTON32782                  32782
#define ID_BUTTON32783                  32783
#define ID_ARROW                        32784
#define ID_BUTTON32785                  32785
#define ID_BUTTON32786                  32786
#define ID_BUTTON32787                  32787
#define ID_BUTTON32791                  32791
#define ID_BUTTON32792                  32792
#define ID_BUTTON32793                  32793
#define ID_BUTTON32794                  32794
#define ID_DRAWLINE                     32795
#define ID_DRAWCIRCLE                   32797
#define ID_DRAW                         32799
#define ID_MAPCHANGE                    32801
#define ID_DELETE                       32802
#define ID_SELECT                       32811
#define ID_SENDAA                       32812
#define ID_SENDAB                       32813
#define ID_SENDCB                       32814
#define ID_SENDCC                       32815
#define ID_SENDCD                       32816
#define ID_SENDDA                       32817
#define ID_VIEW_LISTBAR                 32818
#define ID_DELETELISTITEM               32819
#define ID_CLEARALARM                   32821
#define ID_DUTYRECORD                   32823
#define ID_JIAOBAN                      32824
#define ID_FENJICABLESET                32826
#define ID_USERSET                      32828
#define ID_VIEWDUTYRECORD               32829
#define ID_VIEWFENJICABLEINFO           32830
#define ID_VIEWFENJIALARMINFO           32832
#define ID_VIEWCABLEALARMINFO           32833
#define ID_SENDCA                       32834
#define ID_SENDDC                       32835
#define ID_SETCENTERTEL                 32837
#define ID_TEMP                         32838
#define ID_ONTEMP                       32839
#define ID_CURRENTTIME                  61446
#define ID_LINKSTATE                    61447

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
